substitutions:
  name: esp-garage-v10
  friendly_name: "Garage controller v1.0"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  platformio_options:
    board_build.flash_mode: dio
  
  project:
    name: "ficueu.esp-garage-v10"
    version: "1.0"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:
  # hardware_uart: USB_SERIAL_JTAG
  baud_rate: 0

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:

dashboard_import:
  package_import_url: github://ficueu/ESPHome-IoT-modules/ESP-GARAGE/esp-garage-v10.yaml@main
  import_full_config: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP-GARAGE"
    password: "12345678"

captive_portal:

web_server:
  port: 80
  version: 1
  
light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO10
    num_leds: 10
    rmt_channel: 0
    chipset: ws2812
    name: "LED"
    id: door_led

status_led:
  pin:
    number: 9
    inverted: false

sensor:
  - platform: internal_temperature
    name: "Temperatura modułu"

  - platform: adc
    pin: GPIO0
    name: "Napięcie zasilania"
    update_interval: 10s
    filters:
      - skip_initial: 3
      - multiply: 31
      - round: 1

switch:
  - platform: gpio
    pin: GPIO5
    id: relay1
    name: "Przekaźnik 1"

  - platform: gpio
    pin: GPIO4
    id: relay2
    name: "Przekaźnik 2"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO21
      inverted: true
    name: "IN1"
    id: input1
    filters:
      - delayed_on_off: 50ms

  - platform: gpio
    pin:
      number: GPIO20
      inverted: true
    name: "IN2"
    id: input2
    filters:
      - delayed_on_off: 50ms

button:
  - platform: template
    name: "Przekaźnik 1 impuls"
    id: btn1
    icon: "mdi:gate-open"
    on_press:
      then:
        - switch.turn_on: relay1
        - delay: 500ms
        - switch.turn_off: relay1

  - platform: template
    name: "Przekaźnik 2 impuls"
    id: btn2
    icon: "mdi:gate-open"
    on_press:
      then:
        - switch.turn_on: relay2
        - delay: 500ms
        - switch.turn_off: relay2