substitutions:
  name: esp-garage-v10
  friendly_name: "Garage controller v1.0"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  platformio_options:
    board_build.flash_mode: dio
  
  project:
    name: "ficueu.esp-garage-v10"
    version: "1.0"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:
  # hardware_uart: USB_SERIAL_JTAG
  baud_rate: 0

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:

dashboard_import:
  package_import_url: github://ficueu/ESPHome-IoT-modules/ESP-GARAGE/esp-garage-v10.yaml@main
  import_full_config: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP-GARAGE"
    password: "12345678"

captive_portal:

web_server:
  port: 80
  version: 1
  
light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO10
    num_leds: 10
    rmt_channel: 0
    chipset: ws2812
    name: "LED"
    id: door_led

status_led:
  pin:
    number: 9
    inverted: false

sensor:
  - platform: internal_temperature
    name: "Internal temperature"

  - platform: adc
    pin: GPIO0
    name: "Bus Voltage"
    update_interval: 10s
    filters:
      - skip_initial: 3
      - multiply: 31
      - round: 1

switch:
  - platform: gpio
    pin: GPIO5
    id: relay1
    name: "Przekaźnik 2 skrzydła"

  - platform: gpio
    pin: GPIO4
    id: relay2
    name: "Przekaźnik 1 skrzydło"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO21
      inverted: false
    name: "Wejście kogut"
    id: input1
    filters:
      - delayed_on_off: 50ms
    on_press:
      then:
        - delay: 750ms
        - if:
            condition:
              and:
                - binary_sensor.is_off: input1
                - binary_sensor.is_off: input2
            then:
              - binary_sensor.template.publish:
                  id: door_opening
                  state: OFF
              - binary_sensor.template.publish:
                  id: door_closing
                  state: ON
        - if:
            condition:
                - binary_sensor.is_on: input1
            then:
              - binary_sensor.template.publish:
                  id: door_opening
                  state: ON
              - binary_sensor.template.publish:
                  id: door_closing
                  state: OFF

  - platform: gpio
    pin:
      number: GPIO20
      inverted: true
    name: "Czujnik zamknięcia"
    id: input2
    filters:
      - delayed_on_off: 50ms
    on_press:
      then:
        - binary_sensor.template.publish:
            id: door_opening
            state: OFF
        - binary_sensor.template.publish:
            id: door_closing
            state: OFF
        - light.turn_off:
            id: door_led

  - platform: template
    name: "Otwieranie bramy"
    id: door_opening
    on_press:
      then:
        - light.turn_on:
            id: door_led
            effect: Slow Pulse
            brightness: 50%
            red: 0%
            green: 100%
            blue: 0%

  - platform: template
    name: "Zamykanie bramy"
    id: door_closing
    on_press:
      then:
        - light.turn_on:
            id: door_led
            effect: Fast Pulse
            brightness: 50%
            red: 100%
            green: 0%
            blue: 0%


button:
  - platform: template
    name: "Cała brama1"
    id: btn1
    icon: "mdi:gate-open"
    on_press:
      then:
        - switch.turn_on: relay1

  - platform: template
    name: "Połowa bramy1"
    id: btn2
    icon: "mdi:gate-open"
    on_press:
      then:
        - switch.turn_on: relay2