esphome:
  name: esp-bresser-v10
  friendly_name: ESP-BRESSER-v10

  platformio_options:
    board_build.flash_mode: dio
    lib_ldf_mode: chain

  libraries:
    - jgromes/RadioLib


  includes:
    - bresser-radiolib.h

  project:
    name: "ficueu.esp-bresser-v10"
    version: "1.0"

  name_add_mac_suffix: true
  

dashboard_import:
  package_import_url: github://ficueu/ESPHome-IoT-modules/ESP-MBUS/esp-bresser-v10.yaml@main
  import_full_config: true

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:
  level: DEBUG
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

status_led:
  pin:
    number: 10
    inverted: false
    
sensor:
- platform: custom
  lambda: |-  
    auto my_Bresser = new Bresser();
    App.register_component(my_Bresser);
    return {
      my_Bresser->temperature_sensor, 
      my_Bresser->humidity_sensor,
      my_Bresser->wind_avg_sensor,
      my_Bresser->wind_gust_sensor,
      my_Bresser->wind_dir_sensor,
      my_Bresser->rain_sensor,
      my_Bresser->battery_sensor
      };
    
  sensors:
  - name: "Temperatura"
    unit_of_measurement: '°C'
    icon: mdi:thermometer
    accuracy_decimals: 1

  - name: "Wilgotność"
    icon: mdi:water-percent
    unit_of_measurement: '%'
    accuracy_decimals: 0

  - name: "Prędkość wiatru"
    unit_of_measurement: "m/s"
    accuracy_decimals: 1
    icon: mdi:wind-turbine

  - name: "Porywy wiatru"
    unit_of_measurement: "m/s"
    accuracy_decimals: 1
    icon: mdi:weather-windy

  - name: "Kierunek wiatru"
    unit_of_measurement: "°"
    accuracy_decimals: 1
    icon: mdi:compass-rose
  
  - name: "Deszcz"
    unit_of_measurement: "mm"
    accuracy_decimals: 1
    icon: mdi:weather-pouring

  - name: "Bateria"
    accuracy_decimals: 0
    icon: mdi:battery
