substitutions:
  name: "esp-mbus"
  friendly_name: ESP32C3 CC1101 MBUS GATEWAY v1.0

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ficueu.esp-mbus-v10"
    version: "1.0"
  
  name_add_mac_suffix: false

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:
  level: DEBUG
  baud_rate: 0

dashboard_import:
  package_import_url: github://ficueu/ESPHome-IoT-modules/ESP-MBUS/esp-mbus-v10.yaml@main
  import_full_config: true

api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP-MBUS"
    password: "12345678"

captive_portal:

web_server:
  port: 80
  version: 1
  

external_components:
  - source: github://SzczepanLeon/esphome-components@version_4
    components: [ wmbus ]

time:
  - platform: sntp
    id: time_sntp

wmbus:
  mosi_pin: GPIO5
  miso_pin: GPIO4
  clk_pin:  GPIO6
  cs_pin:   GPIO7
  gdo0_pin: GPIO3
  gdo2_pin: GPIO1

  all_drivers: false
  log_all: True
  #sync_mode: true
  frequency: 868.950

status_led:
  pin:
    number: 10
    inverted: false