substitutions:
  name: esp-poe-mm-v13-rs-can
  friendly_name: ESP32 PoE Multi Gateway v1.2 (RS485+CAN)


esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

  #name_add_mac_suffix: true

  project:
    name: "ficueu.esp-poe-mm-v13-rs-can"
    version: "1.3"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

dashboard_import:
  package_import_url: github://ficueu/ESPHome-IoT-modules/ESP-POE-MM-v1.0/esp-poe-mm-v13-rs-can.yaml@main
  import_full_config: true

logger:

api:
  reboot_timeout: 0s

ota:
  
web_server:
  port: 80
  version: 1

status_led:
  pin:
    number: 2
    inverted: true

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 1
  power_pin: GPIO12
  
  
#UART Settings
uart:  
  - id: RS485_1
    rx_pin: GPIO39
    tx_pin: GPIO14
    baud_rate: 9600   

modbus:
  - id: MODBUS1
    flow_control_pin: 13  
    uart_id: RS485_1

button:
  - platform: restart
    name: "Gateway restart"

modbus_controller:
  - id: mod1
    address: 0x01   ## address of the ModBUS slave device on the bus
    modbus_id: MODBUS1
    setup_priority: -20
    update_interval: 10s

sensor:
  - platform: modbus_controller
    modbus_controller_id: mod1
    name: mod1value
    id: mod1val
    register_type: holding
    address: 79
    value_type: U_WORD

canbus:
  - platform: esp32_can
    tx_pin: GPIO4
    rx_pin: GPIO5
    can_id: 10
    bit_rate: 125kbps
    on_frame:
      - can_id: 100
        then:
        - lambda: |-
            std::string b(x.begin(), x.end());
            ESP_LOGD("canid 500", "%s", &b[0] );

esp32_ble_tracker:
 scan_parameters:
   interval: 1100ms
   window: 1100ms

bluetooth_proxy:
 active: true