esphome:
  name: esp-poe-mm-v10
  friendly_name: esp-poe-mm-v1.0

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

status_led:
  pin:
    number: 2
    inverted: true
    
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 1
  power_pin: GPIO12
  
  
#UART Settings
uart:
  - id: RS1
    rx_pin: GPIO34
    tx_pin: GPIO15
    baud_rate: 9600

  - id: RS2
    rx_pin: GPIO39
    tx_pin: GPIO14
    baud_rate: 9600       

modbus:
  - id: MODBUS1
    flow_control_pin: 13  
    uart_id: RS1
  - id: MODBUS2
    flow_control_pin: 16  
    uart_id: RS2

canbus:
  - platform: esp32_can
    tx_pin: GPIO5
    rx_pin: GPIO4
    can_id: 1
    bit_rate: 500kbps
  
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms

bluetooth_proxy:
  active: true