substitutions:
  name: esp-poe-mm-v12-2rs
  friendly_name: ESP32 PoE Multi Gateway v1.2 (2xRS485)


esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

  #name_add_mac_suffix: true

  project:
    name: "ficueu.esp-poe-mm-v12-2rs"
    version: "1.2"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

dashboard_import:
  package_import_url: github://ficueu/ESPHome-IoT-modules/ESP-POE-MM-v1.0/esp-poe-mm-v12-2rs.yaml@main
  import_full_config: true

logger:

api:
  reboot_timeout: 0s

ota:
  
web_server:
  port: 80
  version: 1

status_led:
  pin:
    number: 2
    inverted: true




ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 1
  power_pin: GPIO12
  
  
#UART Settings
uart:  
  - id: RS485_1
    rx_pin: GPIO39
    tx_pin: GPIO14
    baud_rate: 9600
    debug:

  - id: RS485_2
    rx_pin: GPIO36
    tx_pin: GPIO15
    baud_rate: 9600   

modbus:
  - id: MODBUS1
    flow_control_pin: 13  
    uart_id: RS485_1

  - id: MODBUS2
    flow_control_pin: 16  
    uart_id: RS485_2

external_components:
  - source: github://oxan/esphome-stream-server

button:
  - platform: restart
    name: "Gateway restart"

    
# esp32_ble_tracker:
#  scan_parameters:
#    interval: 1100ms
#    window: 1100ms

# bluetooth_proxy:
#  active: true

modbus_controller:
  
  - id: epever2
    address: 0x01   ## address of the ModBUS slave device on the bus
    modbus_id: MODBUS2
    setup_priority: -10

sensor:
  - platform: uptime
    name: GW uptime

  - platform: modbus_controller
    modbus_controller_id: epever2
    name: "idx0"
    register_type: coil
    address: 0x0
    bitmask: 0x0
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: epever2
    name: "idx1"
    register_type: coil
    address: 0x0
    bitmask: 0x1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: epever2
    name: "idx2"
    register_type: coil
    address: 0x0
    bitmask: 0x2
    value_type: U_WORD

