substitutions:
  name: esp-poe-mm-v14-mbus
  friendly_name: ESP32 PoE Multi Gateway v1.4 (MBUS)

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

  name_add_mac_suffix: true

  project:
    name: ficueu.esp-poe-mm-v14-mbus
    version: '1.4'

esp32:
  board: esp32dev
  framework:
    type: arduino

dashboard_import:
  package_import_url: 
    github://ficueu/ESPHome-IoT-modules/ESP-POE-MM-v1.0/esp-poe-mm-v14-mbus.yaml@main
  import_full_config: true

external_components:
  - source: github://SzczepanLeon/esphome-components@main
    components: [ wmbus ]

logger:

api:

ota:
  platform: esphome

status_led:
  pin:
    number: 2
    inverted: true

sensor:
  - platform: uptime
    name: "GW uptime"

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 1
  power_pin: GPIO12


time:
  - platform: sntp
    id: time_sntp


wmbus:
  mosi_pin: GPIO5
  miso_pin: GPIO4
  clk_pin:  GPIO13
  cs_pin:   GPIO14
  gdo0_pin: GPIO33
  gdo2_pin: GPIO35