substitutions:
  name: "esp-rgbww-v11c2"
  friendly_name: "ESP32 RGBWW v.1.1"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  platformio_options:
    board_build.flash_mode: dio
  
  name_add_mac_suffix: true
  
  project:
    name: "ficueu.esp-rgbww-v11c2"
    version: "1.1"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
  platform: esphome

dashboard_import:
  package_import_url: github://ficueu/ESPHome-IoT-modules/ESP-RGBWW/esp-rgbww-v11c2.yaml@main
  import_full_config: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP-RGBWW"
    password: "12345678"

captive_portal:

web_server:
  port: 80
  version: 2
  
light:
  - platform: monochromatic
    name: "LED1"
    output: output1
  - platform: monochromatic
    name: "LED2"
    output: output2
  - platform: monochromatic
    name: "LED3"
    output: output3
  - platform: monochromatic
    name: "LED4"
    output: output4
  - platform: monochromatic
    name: "LED5"
    output: output5

  # - platform: rgbww
  #   name: "RGBWW"
  #   red: output1
  #   green: output2
  #   blue: output3
  #   cold_white: output4
  #   warm_white: output5
  #   cold_white_color_temperature: 6536 K
  #   warm_white_color_temperature: 2000 K

  # - platform: esp32_rmt_led_strip
  #   rgb_order: GRB
  #   pin: GPIO7
  #   num_leds: 10
  #   rmt_channel: 0
  #   chipset: ws2812
  #   name: "WS2812 on GPIO7 (IN4)"

output:
  - platform: ledc
    id: output1
    pin: GPIO7
    frequency: 4000
  - platform: ledc
    id: output2
    pin: GPIO3
    frequency: 4000
  - platform: ledc
    id: output3
    pin: GPIO10
    frequency: 4000
  - platform: ledc
    id: output4
    pin: GPIO5
    frequency: 4000
  - platform: ledc
    id: output5
    pin: GPIO4
    frequency: 4000
    
status_led:
  pin:
    number: 9
    inverted: false

sensor:
  - platform: internal_temperature
    name: "Internal temperature"

  - platform: adc
    pin: GPIO0
    name: LED Voltage
    update_interval: 10s
    filters:
    - skip_initial: 3
    - multiply: 31
    - round: 1

  - platform: adc
    pin: GPIO1
    name: "LED Current"
    unit_of_measurement: "A"
    update_interval: 10s
    attenuation: 6db
    filters:
      - skip_initial: 3
      - calibrate_linear:
          datapoints:
            - 0.010 -> 0.0
            - 0.018 -> 1.0
            - 0.288 -> 10.0
      - round: 1
      - lambda: |-
          if (x >= 0.5) return x;
          else return 0;