substitutions:
  name: "esp-rgbww-v10"
  friendly_name: "ESP32 RGBWW v.1.0"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  platformio_options:
    board_build.flash_mode: dio
  
  project:
    name: "ficueu.esp-rgbww-v10"
    version: "1.0"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:
  platform: esphome

dashboard_import:
  package_import_url: github://ficueu/ESPHome-IoT-modules/ESP-RGBWW/esp-rgbww-v10.yaml@main
  import_full_config: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP-RGBWW"
    password: "12345678"

captive_portal:

web_server:
  port: 80
  version: 1
  
light:
  - platform: monochromatic
    name: "LED1"
    output: output1
  - platform: monochromatic
    name: "LED2"
    output: output2
  - platform: monochromatic
    name: "LED3"
    output: output3
  - platform: monochromatic
    name: "LED4"
    output: output4
  - platform: monochromatic
    name: "LED5"
    output: output5

  # - platform: rgbww
  #   name: "RGBWW"
  #   red: output1
  #   green: output2
  #   blue: output3
  #   cold_white: output4
  #   warm_white: output5
  #   cold_white_color_temperature: 6536 K
  #   warm_white_color_temperature: 2000 K

  # - platform: esp32_rmt_led_strip
  #   rgb_order: GRB
  #   pin: GPIO7
  #   num_leds: 10
  #   rmt_channel: 0
  #   chipset: ws2812
  #   name: "WS2812 on GPIO7 (IN4)"

output:
  - platform: ledc
    id: output1
    pin: GPIO0
  - platform: ledc
    id: output2
    pin: GPIO1
  - platform: ledc
    id: output3
    pin: GPIO3
  - platform: ledc
    id: output4
    pin: GPIO4
  - platform: ledc
    id: output5
    pin: GPIO5
    
status_led:
  pin:
    number: 10
    inverted: false

sensor:
  - platform: internal_temperature
    name: "Internal temperature"
    