substitutions:
  devicename: "esp-acw-haier"
  name: "esp-acw-haier"
  friendly_name: "ESP32C3 ACW v1.0 (Haier)"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  platformio_options:
    board_build.flash_mode: dio
  
  #name_add_mac_suffix: true

  project:
    name: "ficueu.esp-acw-v10-haier"
    version: "1.0"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:
  baud_rate: 0

api:

ota:

dashboard_import:
  package_import_url: github://ficueu/ESPHome-IoT-modules/ESP-ACW/esp-acw-haier.yaml@main
  import_full_config: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP-ACW-HAIER"
    password: "12345678"

captive_portal:

external_components:
  - source: github://paveldn/haier-esphome

status_led:
  pin:
    number: 10
    inverted: false

uart:
    rx_pin: GPIO7
    tx_pin: GPIO6
    baud_rate: 9600
    id: uart_haier
    debug:
      direction: BOTH

climate:
  - platform: haier
    id: haier_ac
    protocol: hOn
    name: "${devicename}" 
    uart_id: uart_haier
    wifi_signal: true           # Optional, default true, enables WiFI signal transmission from ESP to AC
    beeper: true                # Optional, default true, disables beep on commands from ESP
    outdoor_temperature:        # Optional, outdoor temperature sensor
      name: "${devicename} outdoor temp"
    visual:                     # Optional, you can use it to limit min and max temperatures in UI (not working for remote!)
      min_temperature: 16 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    supported_modes:            # Optional, can be used to disable some modes if you don't need them
    - 'OFF'
    - AUTO
    - COOL
    - HEAT
    - DRY
    - FAN_ONLY
    supported_swing_modes:      # Optional, can be used to disable some swing modes if your AC does not support it
    - 'OFF'
    - VERTICAL
    - HORIZONTAL
    - BOTH

button:
  - platform: template
    name: "${devicename} health on (uvc)"
    on_press:
      then:
        - climate.haier.health_on: haier_ac
  - platform: template
    name: "${devicename} health off (uvc)"
    on_press:
      then:
        - climate.haier.health_off: haier_ac
  - platform: template
    name: "${devicename} self-cleaning"
    on_press:
      then:
        - climate.haier.start_self_cleaning: haier_ac
  - platform: template
    name: "${devicename} steri-cleaning"
    on_press:
      then:
        - climate.haier.start_steri_cleaning: haier_ac
  - platform: template
    name: "${devicename} beeper on"
    on_press:
      then:
        - climate.haier.beeper_on: haier_ac
  - platform: template
    name: "${devicename} beeper off"
    on_press:
      then:
        - climate.haier.beeper_off: haier_ac
  - platform: template
    name: "${devicename} display off"
    on_press:
      then:
        - climate.haier.display_off: haier_ac
  - platform: template
    name: "${devicename} display on"
    on_press:
      then:
        - climate.haier.display_on: haier_ac    