substitutions:
  name: "esp-acw-haier"
  friendly_name: "ESP32C3 ACW v1.0 (Haier)"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  platformio_options:
    board_build.flash_mode: dio
  
  #name_add_mac_suffix: true

  project:
    name: "ficueu.esp-acw-v10-haier"
    version: "1.0"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:
  baud_rate: 0

api:

ota:

web_server:
  port: 80
  version: 1

dashboard_import:
  package_import_url: github://ficueu/ESPHome-IoT-modules/ESP-ACW/esp-acw-haier.yaml@main
  import_full_config: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP-ACW-HAIER"
    password: "12345678"

captive_portal:

external_components:
  - source: github://paveldn/haier-esphome

status_led:
  pin:
    number: 10
    inverted: false

uart:
    rx_pin: GPIO7
    tx_pin: GPIO6
    baud_rate: 9600
    id: uart_haier
    debug:
      direction: BOTH

climate:
  - platform: haier
    id: haier_ac
    protocol: hOn
    name: "Klimatyzacja" 
    uart_id: uart_haier
    wifi_signal: true           # Optional, default true, enables WiFI signal transmission from ESP to AC
    beeper: true                # Optional, default true, disables beep on commands from ESP
    outdoor_temperature:        # Optional, outdoor temperature sensor
      name: "Temperatura zewnętrzna"
    visual:                     # Optional, you can use it to limit min and max temperatures in UI (not working for remote!)
      min_temperature: 16 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    supported_modes:            # Optional, can be used to disable some modes if you don't need them
    - 'OFF'
    - AUTO
    - COOL
    - HEAT
    - DRY
    - FAN_ONLY
    supported_swing_modes:      # Optional, can be used to disable some swing modes if your AC does not support it
    - 'OFF'
    - VERTICAL
    - HORIZONTAL
    - BOTH

button:
  - platform: template
    name: "Health on (uvc)"
    on_press:
      then:
        - climate.haier.health_on: haier_ac
  - platform: template
    name: "Health off (uvc)"
    on_press:
      then:
        - climate.haier.health_off: haier_ac
  - platform: template
    name: "Self-cleaning"
    on_press:
      then:
        - climate.haier.start_self_cleaning: haier_ac
  - platform: template
    name: "Steri-cleaning"
    on_press:
      then:
        - climate.haier.start_steri_cleaning: haier_ac
  - platform: template
    name: "Beeper on"
    on_press:
      then:
        - climate.haier.beeper_on: haier_ac
  - platform: template
    name: "Beeper off"
    on_press:
      then:
        - climate.haier.beeper_off: haier_ac
  - platform: template
    name: "Display off"
    on_press:
      then:
        - climate.haier.display_off: haier_ac
  - platform: template
    name: "Display on"
    on_press:
      then:
        - climate.haier.display_on: haier_ac

select:
  - platform: template
    id: nawiew_poziomy
    name: "Nawiew poziomy"
    entity_category: config
    icon: mdi:arrow-expand-horizontal
    optimistic: true
    restore_value: true
    initial_option: Środek 
    options:
      - Mocno lewo
      - Lewo
      - Środek
      - Prawo
      - Mocno prawo
    on_value:
      then:
        - climate.haier.set_horizontal_airflow:
           id: haier_ac
           horizontal_airflow: !lambda |-
             return esphome::haier::AirflowHorizontalDirection(i);
  
  - platform: template
    id: nawiew_pionowy
    name: "Nawiew pionowy"
    entity_category: config
    icon: mdi:arrow-expand-vertical
    optimistic: true
    restore_value: true
    initial_option: Środek 
    options:
      - Zdrowy góra
      - Mocno góra
      - Góra
      - Środek
      - Dół
      - Zdrowy dół
    on_value:
      then:
        - climate.haier.set_vertical_airflow:
           id: haier_ac
           vertical_airflow: !lambda |-
             return esphome::haier::AirflowVerticalDirection(i);