substitutions:
  name: "esp-intf-v10"
  friendly_name: "Interface module (RS485, CAN, 2xBIN)"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ficueu.esp-intf-v10"
    version: "1.0"

  # name_add_mac_suffix: true
  
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

dashboard_import:
  package_import_url: github://ficueu/ESPHome-IoT-modules/ESP-INTF/esp-intf-v10.yaml@main
  import_full_config: true

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP-INTF"
    password: "12345678"

captive_portal:

web_server:
  port: 80
  version: 1
  
status_led:
  pin:
    number: 9
    inverted: false

uart:
  id: mod_bus
  tx_pin: 21
  rx_pin: 20
  baud_rate: 9600
  debug:


canbus:
  - platform: esp32_can
    tx_pin: GPIO3
    rx_pin: GPIO4
    can_id: 100
    bit_rate: 125kbps

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      inverted: true
    name: "Input1"
    id: input1
    filters:
      - delayed_on_off: 50ms
    
  - platform: gpio
    pin:
      number: GPIO6
      inverted: true
    name: "Input2"
    id: input2
    filters:
      - delayed_on_off: 50ms