substitutions:
  name: pump-driver-v1
  friendly_name: Pump pwm driver v1.0
  led_brightness: 50%
  
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ficueu.esp-pwm-v10"
    version: "1.0"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

dashboard_import:
  package_import_url: github://ficueu/ESPHome-IoT-modules/ESP-PWM/esp-pwm-v10.yaml@main
  import_full_config: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "ESP-PWM"
    password: "12345678"

captive_portal:

status_led:
  pin:
    number: 10
    inverted: false


web_server:
  version: 1
  port: 80


output:
  - platform: ledc
    pin: GPIO6
    id: PWM_TX
    inverted: true
    frequency: 200Hz

fan:
  - platform: speed
    output: PWM_TX
    name: "Zadany PWM"

sensor:
  - platform: pulse_width
    pin: GPIO7
    name: "Odczytany PWM [RAW]"
    id: pump_pwm_read_raw
    update_interval: 10s
    on_value:
      - sensor.template.publish:
          id: pump_pwm_read
          state: !lambda 'return (id(pump_pwm_read_raw).state/0.01333)*100;' 

  - platform: template
    name: "Odczytany PWM [%]"
    id: pump_pwm_read